[package]
name = "remotely-zod-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc_macro = true

[dependencies]
darling = "0.14.3"
pretty_assertions = "1.3.0"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.51"
quote = "1.0.23"
serde_derive_internals = "0.26.0"
syn = "1.0.107"
