[package]
name = "remotely-core"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.64"
inventory = "0.3.3"
serde = "1.0.152"
serde_json = "1.0.92"
ts-rs = "6.2.1"
futures = "0.3.26"
pin-project-lite = "0.2.9"
thiserror = "1.0.38"
tokio = "1.25.0"
